dist: trusty
sudo: false
language: go
go: 1.x
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: fv0SYzjSQkgU6FfanqE4bckxDvQ8AEw8hwki1WqxMJ2K0mzB6cmlGSTs7UV1LTDbqREB5Rt2WblFFOhg3v/UvCQu1YWPrXn0lrXkVqNmzM2cEzHtQ/uHiX+TNs6yxZ3i2/DtzUX/JaLuxWMrbhSBDY20RVccc0MfEHtjnq92BJG3/I8uCkqvCoEf/Nv+fa4zI2JU0u87WFjDvLeArNaaTiuUJ1WYs6Zm1QHLGvYUUcIvsvCvoadCbHSZivEBfAFhqKMsz11fb+EWLXWxYa/2qBWSBzgVC6u5yuztUBIIaEbktg53WWj48eKuo3KDWiMR60tt8CZvSyaLwU5KdxdCFw8tvB91jZKsd0/xYLyGIOyMhtc+CcLzZaRMx7yJ87R1Mzm+j8/mQNqCY6PLhQI+Nkbs3axe0vdUAGnTRe+RcS/i/f4j+Qysv/GX1tmlQfTiBo0dCyTVkAC4jkZGcgIn9WVjLHeNIqQhtWPGiPQ4pMSiHGT+/fzmFVhn+lQ/W/oHFT2+IaQY2+haQbzP/h+tCeOM1G8017q2PDSfOZh8oTpazTxOu3JHhfI8sAxlwvQqcn5Lq+3ADYsKhwCMXfE4mabX8SmP1TDHXtnKhMOgrXMNC7GYPnAl6LST2eD4iWrFkjM1J8Yc1tboOrIh0b+Mr3XwlBsAWJgl20b3UppF1g8=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
